'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property idEmpleado As Integer
    Public Property usuario As String
    Public Property contraseña As String
    Public Property fechaAlta As Date
    Public Property telefono As Nullable(Of Integer)
    Public Property nombre As String
    Public Property apellidos As String
    Public Property cargo As String
    Public Property email As String

    Public Overridable Property TrabajosRealizados As ICollection(Of TrabajosRealizados) = New HashSet(Of TrabajosRealizados)

End Class
